#
# Copyright 2019-2020 Amazon Technologies, Inc. All Rights Reserved.
#
# Gerard Mu (mqiao@amazon.com)
# Zengjin Zhao (zzengjin@amazon.com)
# TODO: Add additional contributor's names.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

obj-$(CONFIG_SND_SOC_RT551X_ADF) += src/cli.o
obj-$(CONFIG_SND_SOC_RT551X_ADF) += src/log.o
obj-$(CONFIG_SND_SOC_RT551X_ADF) += src/ringbuf.o
obj-$(CONFIG_SND_SOC_RT551X_ADF) += src/state.o
obj-$(CONFIG_SND_SOC_RT551X_ADF) += src/load.o

ccflags-y += -I$(srctree)/sound/soc/codecs